# Generated by Django 4.1.2 on 2022-10-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
